from sentence_transformers import SentenceTransformer
import numpy as np

model = SentenceTransformer('all-mpnet-base-v2')

insights = [
    "Poverty, in all its forms, is widespread across Liberia, and has been increasing over the past few years. The ongoing COVID-19 pandemic has contributed to the increasing trend of poverty in Liberia. In 2016, the proportion of Liberians below the international poverty line (US$1.9 in 2011 PPP) stood at 44 percent. As shown in the table above, more Liberians have fallen into extreme poverty over the past few years. The World Bank’s Macro Poverty Outlook (2020) reports that the proportion of Liberians below the international poverty line increased to 46.5 percent in 2017 and reduced slightly to 45.7 percent in 2018. In 2019, the proportion of Liberians living on less than US$1.9 a day increased to 49.4 percent. In 2020, the proportion further increased to 51.1 percent, and is expected to drop to 50.6 percent in 2021 (Macro Poverty Outlook, 2022). The World Bank estimates that extreme poverty will reduce slightly to 49.4 percent in 2022. The 2021 United Nations multidimensional poverty index establishes 52.3 percent as multi-dimensional poor, which translates into 2.6 million poor. [Citation: VNRReport, page 1]",
    "In 2020, a rapid assessment conducted by the Government of Liberia (GOL) and the United Nations indicated that the impact of the COVID-19 shock is expected to be greater in urban areas. The study estimated that urban poverty will increase by 10.9 percent in contrast to a 4.7 percent increase in rural areas, and that a majority (59.9 percent) of the new poor will be in urban areas of Liberia, especially Montserrado County.",
    "In terms of distribution, the incidence of extreme poverty is most widely spread in Liberia’s rural areas. Per the HIES (2016), the incidence of poverty in rural Liberia was 71.6 percent, compared to 31.5 percent in urban areas. However, the rural-urban distribution of poverty has been shifted by COVID-19.",
    "Liberia has made improvement in access to basic services, with access to electricity rising from 10 percent in 2013 to 24 percent in 2019–2020. Additionally, access to improved drinking water rose from 73 percent in 2013 to 84 percent in 2019–2020. Access to improved toilet facilities moved by 30 percentage points, from 17 percent in 2013 to 47 percent in 2019–2020",
    "The impact of the COVID-19 pandemic has been detrimental to efforts aimed at reducing poverty, as evidenced by the increased rates of poverty and the shift in its rural-urban distribution.",
    "Access to basic services is crucial for poverty reduction, yet many populations, especially in rural areas, still face significant barriers, including limited infrastructure and resources.",
    "The incidence of poverty in urban areas has significantly increased, largely due to the economic impacts brought about by the COVID-19 pandemic.",
    "Challenges in achieving SDG 1 include financial constraints, political barriers, resource limitations, and technological gaps, which affect the effective implementation of poverty reduction strategies.",
    "Poverty, in all its forms, is widespread across Liberia, and has been increasing over the past few years. The ongoing COVID-19 pandemic has contributed to the increasing trend of poverty in Liberia. In 2016, the proportion of Liberians below the international poverty line (US$1.9 in 2011 PPP) stood at 44 percent. As shown in the table above, more Liberians have fallen into extreme poverty over the past few years. [Page 25]",
    "The World Bank’s Macro Poverty Outlook (2020) reports that the proportion of Liberians below the international poverty line increased to 46.5 percent in 2017 and reduced slightly to 45.7 percent in 2018. In 2019, the proportion of Liberians living on less than US$1.9 a day increased to 49.4 percent. [Page 25]",
    "In 2020, the proportion further increased to 51.1 percent, and is expected to drop to 50.6 percent in 2021 (Macro Poverty Outlook, 2022). [Page 25]",
    "The World Bank estimates that extreme poverty will reduce slightly to 49.4 percent in 2022. The 2021 United Nations multidimensional poverty index establishes 52.3 percent as multi-dimensional poor, which translates into 2.6 million poor. [Page 25]",
    "The United Nations estimates that the population in severe multidimensional poverty is 24.9 percent and population vulnerable to multidimensional poverty is 23.3 percent. In terms of distribution, the incidence of extreme poverty is most widely spread in Liberia’s rural areas. [Page 25]",
    "Per the HIES (2016), the incidence of poverty in rural Liberia was 71.6 percent, compared to 31.5 percent in urban areas. However, the rural-urban distribution of poverty has been shifted by COVID-19. [Page 25]",
    "In 2020, a rapid assessment conducted by the GOL and United Nations indicated that the impact of the COVID-19 shock is expected to be greater in urban areas. The study estimated that urban poverty will increase by 10.9 percent in contrast to a 4.7 percent increase in rural areas, and that the majority (59.9 percent) of the new poor will be in urban areas of Liberia, especially in Montserrado County. [Page 26]",
    "Liberia has made improvement in access to basic services with access to electricity rising from 10 percent in 2013 to 24 percent in 2019–2020. Additionally, access to improved drinking water rose from 73 percent in 2013 to 84 percent in 2019–2020. Access to improved toilet facilities moved by 30 percentage points, from 17 percent in 2013 to 47 percent in 2019–2020. [Page 26]",
    "In the 2021 Global Hunger Index (GHI), Liberia ranks 110th out of the 116 countries, with a score of 33.3 points out of 100. The ranking and corresponding score imply that Liberia has a level of hunger that is serious. [Page 29]",
    "On April 7, 2022, the Global Hunger Index report was released by Welthungerhilfe and Concern Worldwide in Monrovia. The report revealed that even though Liberia’s GHI score has decreased by 14.8 points since 2000, hunger is still categorized as serious in the country. [Page 29]",
    "In 2021, the GOL provided preventive nutrition services across 514 health facilities in 2021 (up from 228 in 2020). In total, 244,273 caregivers of children aged 0–23 months received infant and young child feeding counseling; 140,676 pregnant women received iron folic acid (IFA) supplementation; and 171,616 children aged 6–23 months received micronutrient powder supplementation. For the first time, an adolescent nutrition program was introduced and piloted in 124 schools. The package included weekly IFA supplementation, twice yearly deworming, and nutrition education for adolescent girls. The reopening of schools in January 2021 enabled acceleration of the program, which reached 30,077 adolescent girls (above the 18,080 target). [Page 29]",
    "Table 3: Proportion of population with access to basic services—electricity, improved drinking water, and improved toilet facilities. Proportion of population with access to electricity: 10 percent (2013), 24 percent (2019–2020). Proportion of population with access to improved drinking water: 73 percent (2013), 84 percent (2019–2020)."
    "Poverty, in all its forms, is widespread across Liberia, and has been increasing over the past few years. The ongoing COVID-19 pandemic has contributed to the increasing trend of poverty in Liberia. In 2016, the proportion of Liberians below the international poverty line (US$1.9 in 2011 PPP) stood at 44 percent. As shown in the table above, more Liberians have fallen into extreme poverty over the past few years. The World Bank’s Macro Poverty Outlook (2020) reports that the proportion of Liberians below the international poverty line increased to 46.5 percent in 2017 and reduced slightly to 45.7 percent in 2018. In 2019, the proportion of Liberians living on less than US$1.9 a day increased to 49.4 percent. In 2020, the proportion further increased to 51.1 percent, and is expected to drop to 50.6 percent in 2021 (Macro Poverty Outlook, 2022). (Page 1)",
    "The World Bank estimates that extreme poverty will reduce slightly to 49.4 percent in 2022. The 2021 United Nations multidimensional poverty index establishes 52.3 percent as multi-dimensional poor, which translates into 2.6 million poor. In 2019, the number of multidimensional poor was estimated at 2.5 million. The United Nations estimates that the population in severe multidimensional poverty is 24.9 percent and population vulnerable to multidimensional poverty is 23.3 percent. (Page 1)",
    "In terms of distribution, the incidence of extreme poverty is most widely spread in Liberia’s rural areas. Per the HIES (2016), the incidence of poverty in rural Liberia was 71.6 percent, compared to 31.5 percent in urban areas. However, the rural-urban distribution of poverty has been shifted by COVID-19. (Page 1)",
    "In 2020, a rapid assessment conducted by the GOL and United Nations indicated that the impact of the COVID-19 shock is expected to be greater in urban areas. The study estimated that urban poverty will increase by 10.9 percent in contrast to a 4.7 percent increase in rural areas, and that majority (59.9 percent) of the new poor will be in urban areas of Liberia, especially in Montserrado County. (Page 2)",
    "Liberia has made improvement in access to basic services with access to electricity rising from 10 percent in 2013 to 24 percent in 2019–2020. Additionally, access to improved drinking water rose from 73 percent in 2013 to 84 percent in 2019–2020. Access to improved toilet facilities moved by 30 percentage points, from 17 percent in 2013 to 47 percent in 2019–2020. (Page 2)",
    "Liberia’s progress in improving nutritional status is indicative of strong commitments, collaboration, and partnership. In 2014, Liberia became the 47th country to commit to scaling up nutrition with the SUN Movement, which is comprised of sixty-five countries leading a global movement to end malnutrition in all its forms. As a SUN member country, Liberia remains committed to reducing malnutrition through multi-sectoral strategies aimed at tackling and addressing the immediate and underlying causes of malnutrition. Liberia has also effectively harnessed other coordination mechanisms and multi-sectoral platforms such as the United Nations Renewed Efforts Against Child Hunger and Under-nutrition (UN-REACH). (Page 4)",
    "In 2021, the GOL provided preventive nutrition services across 514 health facilities (up from 228 in 2020). In total, 244,273 caregivers of children aged 0–23 months received infant and young child feeding counseling; 140,676 pregnant women received iron folic acid (IFA) supplementation; and 171,616 children aged 6–23 months received micronutrient powder supplementation. For the first time, an adolescent nutrition program was introduced and piloted in 124 schools. The package included weekly IFA supplementation, twice yearly deworming, and nutrition education for adolescent girls. The reopening of schools in January 2021 enabled acceleration of the school adolescent nutrition program, which reached 30,077 adolescent girls (above the 18,080 target). (Page 5)",
    "In 2019, the GOL developed a gender-responsive planning and budgeting (GRPB) policy. The policy guides the GOL on how to advance gender equality and contribute to equitable service delivery and inclusive growth. It outlines the tools and actions for Public Financial Management (PFM) reforms to be gender-responsive for more gender-equal outcomes. In 2021, the GOL provided capacity-building training to PFM stakeholders at national and county levels on how to mainstream gender in planning and budgeting processes. (Page 22)",
    "The GOL trained 34 CSOs on the links between the FY 2022 National Budget, a policy implementation tool that complements the revised National Gender Policy (2018-2023), and the GRPB Policy. Along this line, the GOL developed gender policies for several institutions in 2021 to guide them in incorporating gender-equality considerations. (Page 22)",
    "To support implementation of the GRPB Policy, the GOL allotted US$380,000 in the FY 2022 national budget to support the institutionalization of gender-responsive budgeting (GRB) in nine ministries. (Page 22)"
    "Poverty, in all its forms, is widespread across Liberia, and has been increasing over the past few years. The ongoing COVID-19 pandemic has contributed to the increasing trend of poverty in Liberia. In 2016, the proportion of Liberians below the international poverty line (US$1.9 in 2011 PPP) stood at 44 percent. As shown in the table above, more Liberians have fallen into extreme poverty over the past few years. The World Bank's Macro Poverty Outlook (2020) reports that the proportion of Liberians below the international poverty line increased to 46.5 percent in 2017 and reduced slightly to 45.7 percent in 2018. In 2019, the proportion of Liberians living on less than US$1.9 a day increased to 49.4 percent. In 2020, the proportion further increased to 51.1 percent, and is expected to drop to 50.6 percent in 2021 (Macro Poverty Outlook, 2022). The World Bank estimates that extreme poverty will reduce slightly to 49.4 percent in 2022. [Citation: VNRReport, Page 1]",
    "In terms of distribution, the incidence of extreme poverty is most widely spread in Liberia's rural areas. Per the HIES (2016), the incidence of poverty in rural Liberia was 71.6 percent, compared to 31.5 percent in urban areas. However, the rural-urban distribution of poverty has been shifted by COVID-19. Table 2: Distribution of poverty by urban/rural. [Citation: VNRReport, Page 1]",
    "In 2020, a rapid assessment conducted by the GOL and United Nations indicated that the impact of the COVID-19 shock is expected to be greater in urban areas. The study estimated that urban poverty will increase by 10.9 percent in contrast to a 4.7 percent increase in rural areas, and that a majority (59.9 percent) of the new poor will be in urban areas of Liberia, especially in Montserrado County. [Citation: VNRReport, Page 2]",
    "Table 3: Proportion of population with access to basic services—proportion of population with access to electricity, proportion of population with access to improved drinking water, proportion of population with access to improved toilet facilities. Liberia has made improvement in access to basic services with access to electricity rising from 10 percent in 2013 to 24 percent in 2019–2020. Additionally, access to improved drinking water rose from 73 percent in 2013 to 84 percent in 2019–2020. Access to improved toilet facilities moved by 30 percentage points, from 17 percent in 2013 to 47 percent in 2019–2020. [Citation: VNRReport, Page 2]",
    "Status of Hunger in Liberia: The increasing levels of poverty in Liberia compel many Liberians to go to bed hungry. Hunger remains a serious policy challenge in Liberia. The most recent data on hunger indicates that hunger remains high. The share of Liberia's population who consume fewer than 2,400 calories per day is approximately 39 percent. [Citation: VNRReport, Page 5]",
    "Liberia's progress in improving nutritional status is indicative of strong commitments, collaboration, and partnership. In 2014, Liberia became the 47th country to commit to scaling up nutrition with the SUN Movement. As a SUN member country, Liberia remains committed to reducing malnutrition through multi-sectoral strategies. Liberia has also harnessed coordination mechanisms such as the United Nations Renewed Efforts Against Child Hunger and Under-nutrition (UN-REACH). [Citation: VNRReport, Page 4]",
    "Food Security and Nutrition: The serious nature of hunger is a result of ongoing food insecurity. COVID-19 has disrupted all four pillars of food security in Liberia—food availability, stability, utilization, and accessibility. [Citation: VNRReport, Page 5]",
    "The 2021 United Nations multidimensional poverty index establishes 52.3 percent as multi-dimensional poor, which translates into 2.6 million poor. In 2019, the number was estimated at 2.5 million. The United Nations estimates that the population in severe multidimensional poverty is 24.9 percent and population vulnerable to multidimensional poverty is 23.3 percent. [Citation: VNRReport, Page 1]",
    "In 2021, the GOL provided preventive nutrition services across 514 health facilities (up from 228 in 2020). In total, 244,273 caregivers of children aged 0–23 months received counseling; 140,676 pregnant women received IFA supplementation; and 171,616 children aged 6–23 months received micronutrient powder supplementation. [Citation: VNRReport, Page 5]",
    "The reopening of schools in January 2021 enabled acceleration of the adolescent nutrition program, which reached 30,077 adolescent girls (above the 18,080 target). [Citation: VNRReport, Page 5]"
    "1) Poverty, in all its forms, is widespread across Liberia and has been increasing over the past few years. The ongoing COVID-19 pandemic has contributed to this trend. In 2016, 44% of Liberians lived below the international poverty line (US$1.9 in 2011 PPP). The World Bank’s Macro Poverty Outlook (2020) reports this increased to 46.5% in 2017, slightly reduced to 45.7% in 2018, then increased to 49.4% in 2019 and 51.1% in 2020, with an expected drop to 50.6% in 2021. Extreme poverty is estimated to slightly reduce to 49.4% in 2022. [Page 1]",
    "2) The 2021 United Nations multidimensional poverty index estimates 52.3% of Liberia’s population as multi-dimensionally poor, which translates to 2.6 million people, up from 2.5 million in 2019. Severe multidimensional poverty is at 24.9%, while 23.3% of the population is vulnerable to multidimensional poverty. Poverty is most widespread in rural areas, with 71.6% in rural Liberia versus 31.5% in urban areas (HIES 2016). [Page 2]",
    "3) COVID-19 has shifted the rural-urban poverty distribution. A 2020 rapid assessment by the Government of Liberia (GOL) and the United Nations estimates urban poverty will increase by 10.9%, compared to 4.7% in rural areas. The majority (59.9%) of the new poor are in urban areas, especially Montserrado County. Rural poverty declined from 71.6% in 2016 to 68% in 2021. [Page 2]",
    "4) Liberia improved access to basic services from 2013 to 2019–2020: electricity access rose from 10% to 24%, access to improved drinking water increased from 73% to 84%, and improved toilet facilities increased from 17% to 47%. [Page 2]",
    "5) Access to basic services varies geographically; urban areas have made more progress, while rural areas lag behind in electricity and sanitation access, highlighting regional disparities. [Page 2]",
    "6) Food insecurity and malnutrition remain significant challenges. The 2022 Global Hunger Index report indicates Liberia’s hunger category as serious, despite a 14.8-point GHI score improvement since 2000. However, the decline in hunger rates has slowed and is expected to rise. [Page 5]",
    "7) In 2021, the GOL provided preventive nutrition services at 514 health facilities (up from 228 in 2020). Services included counseling for 244,273 caregivers of children aged 0–23 months, iron folic acid supplementation for 140,676 pregnant women, and micronutrient powder supplementation for 171,616 children aged 6–23 months. An adolescent nutrition program was introduced in 124 schools and reached 30,077 adolescent girls following school reopenings in January 2021. [Page 5]",
    "8) Infant, child, and under-5 mortality rates are lower in urban areas (57, 30, and 85 deaths per 1,000 live births, respectively) compared to rural areas (69, 36, and 102 deaths per 1,000). [Page 7]",
    "9) In 2019, the GOL allocated US$380,000 in the FY 2022 national budget to support institutionalizing gender-responsive budgeting (GRB). [Page 22]"
    "In addition to using ITNs, many women reported taking preventive malaria drugs. Ninety percent of women with a live birth in the 2 years before the survey reported taking one or more doses of fansidar during their last pregnancy; 70 percent took two or more doses, and 40 percent took three or more doses. [Page 10]  "    
    "• Poverty Rates and Trends: Liberia has seen a rise in extreme poverty in both rural and urban regions, partly driven by ongoing economic vulnerabilities and significantly exacerbated by COVID-19. Estimates from 2016 to 2022 show poverty levels moving from 44 percent to over 50 percent, with a slight projected drop in 2021–2022.",
    "Barriers and Challenges: Financial constraints, political and resource limitations, and technological gaps hinder poverty-reduction efforts. The pandemic has also shifted the rural-urban distribution of poverty, making urban areas like Montserrado County particularly vulnerable.",
    "Targeted Goals and Metrics: Metrics such as the international poverty line, the United Nations multidimensional poverty index, and Global Hunger Index scores underscore the severity of hunger, malnutrition, and overall poverty. Specific targets include reducing the proportion of people living below US$1.9 a day and improving access to basic services (electricity, water, sanitation)",
    "Innovation and Best Practices: Liberia’s commitment to nutrition and gender-responsive budgeting exemplifies innovative approaches. Collaboration with global initiatives such as SUN (Scaling Up Nutrition) and UN-REACH has helped accelerate efforts in combating malnutrition. The introduction of adolescent nutrition programs in schools further indicates the multi-sectoral emphasis on ending poverty and hunger",
    "Stakeholder Engagement: Various actors—government agencies, UN entities, civil society organizations, donors, and the private sector—are involved in the design and implementation of policies and programs. Partnerships and coordination mechanisms have supported capacity-building, infrastructure expansion, and service delivery improvement.",
    "Local and Regional Impact: Disparities persist among Liberia’s rural and urban areas, with rural areas still lagging behind in access to electricity and improved sanitation facilities. Meanwhile, urban poverty levels have spiked due to COVID-19’s economic disruptions. Food insecurity and malnutrition remain critical concerns throughout the country, evidenced by the still-serious Global Hunger Index ranking.  Overall, the data and insights presented across these five themes reflect the multi-faceted nature of SDG 1 in Liberia, highlighting progress made and persistent challenges. Coordinated efforts involving government, civil society, and international partners—through both policy innovation and targeted interventions—remain essential for meeting poverty-reduction targets and ensuring broader development gains."
]

# SDG 1 corpus as one big text
sdg1_corpus = """
1.1 Eradicate extreme poverty for all people everywhere 1.1.1 Proportion of population living below the international poverty line
1.2 Reduce by half the proportion of people living in poverty 1.2.1 Proportion of population living below the national poverty line, 1.2.2 Proportion of people living in poverty in all dimensions
1.3 Implement social protection systems 1.3.1 Proportion of population covered by social protection systems
1.4 Ensure equal access to economic resources and services 1.4.1 Proportion of population with access to basic services, 1.4.2 Proportion of total adult population with secure tenure rights to land
1.5 Build resilience to climate-related disasters 1.5.1 Number of deaths, missing persons, and affected persons due to disasters, 1.5.2 Direct economic loss from disasters, 1.5.3 Number of countries implementing national disaster risk reduction strategies, 1.5.4 Proportion of local governments that adopt local disaster risk reduction strategies
1.6 Strengthen resilience to economic, social, and environmental shocks 1.6.1 Proportion of population living in areas exposed to economic, social, and environmental shocks
1.a Mobilize resources to end poverty 1.a.1 Total official development assistance grants focused on poverty reduction, 1.a.2 Proportion of government spending on essential services
1.b Create sound policy frameworks for poverty reduction 1.b.1 Pro-poor public social spending
"""

def cosine_similarity(vec1, vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

def main():
    # Embed the SDG1 corpus
    sdg1_embedding = model.encode(sdg1_corpus)

    # Embed each insight
    insight_embeddings = model.encode(insights)

    # Calculate similarity scores
    scores = [cosine_similarity(ins_emb, sdg1_embedding) for ins_emb in insight_embeddings]
    
    # Calculate average relevance
    average_relevance = np.mean(scores)

    # Pair insights with scores and sort descending
    ranked_insights = sorted(zip(insights, scores), key=lambda x: x[1], reverse=True)

    # Set a threshold for low relevance highlight
    threshold = 0.6

    print("Ranked Insights by Relevance to SDG 1:\n")
    for insight, score in ranked_insights:
        highlight = "<<< LOW RELEVANCE" if score < threshold else ""
        print(f"Score: {score:.4f} {highlight}\nInsight: {insight}\n")
        
    print(f"\nAverage Relevance Score: {average_relevance:.4f}")

if __name__ == "__main__":
    main()
